[project]
name = "all-pairs-shortest-paths"
version = "0.1.0"
description = "APSP pathway reconstruction algorithm implementation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.5",
]
